# Generated by Django 5.0.6 on 2024-06-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapejob',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='coindata',
            name='coin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_data', to='taskmanager.scrapejob'),
        ),
    ]
