# Generated by Django 5.0.6 on 2024-06-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_remove_scrapejob_updated_at_alter_coindata_coin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='data',
            field=models.TextField(),
        ),
    ]
