# Generated by Django 5.0.6 on 2024-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_coindata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindata',
            name='coin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coindata',
            name='data',
            field=models.JSONField(),
        ),
    ]
